/* One-off: builds public/icons.js from the lucide-static package on jsDelivr.
   Kept out of the app; run it again if the icon list below changes. */
import { writeFile } from 'node:fs/promises';

const NAMES = [
  // nav / identity
  'boxes', 'circle-plus', 'globe', 'shield', 'circle-user', 'log-out', 'log-in', 'user-plus',
  'user', 'lock-keyhole', 'ticket', 'layout-dashboard', 'users', 'history', 'server',
  // instance actions
  'play', 'square', 'rotate-cw', 'power', 'trash-2', 'undo-2', 'arrow-right', 'arrow-left',
  'copy', 'refresh-cw', 'save', 'pencil', 'check', 'check-check', 'x', 'plus', 'rocket',
  'upload', 'folder-up', 'file-up', 'external-link', 'search',
  //状态 / metadata
  'circle-check', 'circle-alert', 'triangle-alert', 'info', 'clock', 'hourglass', 'moon',
  'cpu', 'memory-stick', 'hard-drive', 'network', 'plug', 'link', 'calendar', 'activity',
  'arrow-down-to-line', 'arrow-up-from-line', 'container', 'puzzle', 'file-code', 'files',
  'eye', 'sparkles', 'graduation-cap', 'chevron-right', 'key-round', 'scroll-text', 'terminal',
  'settings', 'wrench', 'gauge', 'folder-open', 'ban', 'inbox', 'list-checks', 'eraser',
  'archive',
  // template categories
  'database', 'gamepad-2', 'clapperboard', 'layers', 'sunrise', 'package',
  // file manager
  'folder', 'file', 'file-text', 'file-pen', 'download', 'folder-plus', 'file-plus',
  'corner-left-up', 'link-2', 'house',
  // live console
  'maximize', 'minimize', 'keyboard', 'text-cursor-input', 'a-large-small', 'arrow-down',
  'chevrons-down', 'circle-help', 'wrap-text',
  // 文本编辑器
  'redo-2', 'arrow-up', 'indent-increase', 'hash', 'corner-down-left',
];

const base = 'https://cdn.jsdelivr.net/npm/lucide-static@1.27.0/icons';
const out = {};
const missing = [];

await Promise.all(
  NAMES.map(async (name) => {
    const res = await fetch(`${base}/${name}.svg`);
    if (!res.ok) return missing.push(name);
    const svg = await res.text();
    const inner = svg
      .replace(/<!--[\s\S]*?-->/g, '')
      .replace(/[\s\S]*?<svg[\s\S]*?>/, '')
      .replace(/<\/svg>\s*$/, '')
      .replace(/\s*\n\s*/g, '')
      .trim();
    if (!inner) return missing.push(name);
    out[name] = inner;
  })
);

if (missing.length) {
  console.error('缺失：', missing.join(', '));
  process.exitCode = 1;
}

const body = Object.keys(out)
  .sort()
  .map((k) => `  '${k}':\n    '${out[k].replace(/'/g, "\\'")}',`)
  .join('\n');

await writeFile(
  new URL('../public/icons.js', import.meta.url),
  `/* ===========================================================================
   icons — a subset of Lucide (lucide.dev), ISC licensed, inlined.
   ---------------------------------------------------------------------------
   Generated by scripts/_fetch-icons.mjs from lucide-static@1.27.0. Inlined
   rather than linked so the panel keeps drawing on a box with no internet,
   which is the whole point of the thing it manages.

   Every glyph is a 24×24 stroke path that inherits \`currentColor\`, so an icon
   next to a label picks up that label's colour for free.
   =========================================================================== */

const PATHS = {
${body}
};

/**
 * @param {string} name  key from PATHS
 * @param {{cls?: string, size?: number|string, title?: string}} [opts]
 *   \`cls\` adds classes (\`lg\` for 1.15em, \`muted\` to fade it); \`title\` makes
 *   the icon a labelled image instead of decoration — only pass it when the
 *   icon stands alone, otherwise the label beside it is read twice.
 */
export function icon(name, { cls = '', size, title } = {}) {
  const d = PATHS[name];
  if (!d) return '';
  const style = size ? \` style="width:\${size};height:\${size}"\` : '';
  const a11y = title ? \` role="img" aria-label="\${title}"\` : ' aria-hidden="true"';
  return \`<svg class="ico \${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor"
    stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"\${style}\${a11y}>\${d}</svg>\`;
}

export const hasIcon = (name) => Object.hasOwn(PATHS, name);
`,
  'utf8'
);

console.log(`写入 ${Object.keys(out).length} 个图标`);
