/**
 * Image catalog. Everything a normal user can deploy without the
 * `allow_custom_image` flag comes from here.
 *
 * env[].generate = 'password' -> a random value is generated when the user
 * leaves the field empty, and shown back on the instance page.
 */
export const TEMPLATES = [
  {
    id: 'nginx',
    name: 'Nginx',
    icon: '🌐',
    iconFile: 'nginx.png',
    category: 'Web',
    image: 'nginx:alpine',
    description: '静态网站 / 反向代理。把文件放进数据卷的 /usr/share/nginx/html 即可。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/share/nginx/html'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'code-server',
    name: 'code-server (VS Code)',
    icon: '🧑‍💻',
    iconFile: 'code-server.svg',
    category: '开发',
    image: 'codercom/code-server:latest',
    description: '浏览器里的 VS Code，工作目录持久化在 /home/coder/project。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web IDE' }],
    env: [
      { key: 'PASSWORD', label: '访问密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/home/coder/project'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'postgres',
    name: 'PostgreSQL 16',
    icon: '🐘',
    iconFile: 'postgresql.png',
    category: '数据库',
    image: 'postgres:16-alpine',
    description: '关系型数据库，数据持久化在 /var/lib/postgresql/data。',
    ports: [{ container: 5432, protocol: 'tcp', label: 'Postgres' }],
    env: [
      { key: 'POSTGRES_USER', label: '用户名', type: 'text', default: 'app', required: true },
      { key: 'POSTGRES_PASSWORD', label: '密码', type: 'password', required: true, generate: 'password' },
      { key: 'POSTGRES_DB', label: '默认数据库', type: 'text', default: 'app' },
    ],
    volumes: ['/var/lib/postgresql/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'mysql',
    name: 'MySQL 8',
    icon: '🐬',
    iconFile: 'mysql.svg',
    category: '数据库',
    image: 'mysql:8',
    description: '经典 MySQL，数据持久化在 /var/lib/mysql。',
    ports: [{ container: 3306, protocol: 'tcp', label: 'MySQL' }],
    env: [
      { key: 'MYSQL_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
      { key: 'MYSQL_DATABASE', label: '默认数据库', type: 'text', default: 'app' },
      { key: 'MYSQL_USER', label: '普通用户', type: 'text', default: 'app' },
      { key: 'MYSQL_PASSWORD', label: '普通用户密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/var/lib/mysql'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'redis',
    name: 'Redis 7',
    icon: '🔴',
    iconFile: 'redis.png',
    category: '数据库',
    image: 'redis:7-alpine',
    description: '内存 KV，开启 AOF 持久化到 /data。',
    cmd: ['redis-server', '--appendonly', 'yes'],
    ports: [{ container: 6379, protocol: 'tcp', label: 'Redis' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'mongo',
    name: 'MongoDB 7',
    icon: '🍃',
    iconFile: 'mongodb.png',
    category: '数据库',
    image: 'mongo:7',
    description: '文档数据库，数据在 /data/db。',
    ports: [{ container: 27017, protocol: 'tcp', label: 'MongoDB' }],
    env: [
      { key: 'MONGO_INITDB_ROOT_USERNAME', label: 'root 用户', type: 'text', default: 'root', required: true },
      { key: 'MONGO_INITDB_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/data/db'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'minecraft',
    name: 'Minecraft Java 服务器',
    icon: '⛏️',
    iconFile: 'minecraft-java.png',
    category: '游戏',
    image: 'itzg/minecraft-server:latest',
    description: '开箱即用的 MC 服务端，世界存档在 /data。首次启动需要几分钟下载核心。',
    ports: [{ container: 25565, protocol: 'tcp', label: 'Minecraft' }],
    env: [
      { key: 'EULA', label: '同意 EULA', type: 'select', options: ['TRUE'], default: 'TRUE', required: true },
      { key: 'TYPE', label: '服务端类型', type: 'select', options: ['VANILLA', 'PAPER', 'FABRIC', 'FORGE'], default: 'PAPER' },
      { key: 'VERSION', label: '版本', type: 'text', default: 'LATEST' },
      { key: 'MEMORY', label: 'JVM 内存', type: 'text', default: '1500M' },
      { key: 'MAX_PLAYERS', label: '最大玩家数', type: 'text', default: '10' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'gitea',
    name: 'Gitea',
    icon: '🍵',
    iconFile: 'gitea.svg',
    category: '开发',
    image: 'gitea/gitea:latest',
    description: '轻量自建 Git 服务，含 Web 界面。',
    ports: [
      { container: 3000, protocol: 'tcp', label: 'Web' },
      { container: 22, protocol: 'tcp', label: 'SSH' },
    ],
    env: [{ key: 'USER_UID', label: 'UID', type: 'text', default: '1000' }],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    icon: '📈',
    iconFile: 'uptimekuma.svg',
    category: '工具',
    image: 'louislam/uptime-kuma:1',
    description: '好看的服务可用性监控面板。',
    ports: [{ container: 3001, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    icon: '🔐',
    iconFile: 'vaultwarden.svg',
    category: '工具',
    image: 'vaultwarden/server:latest',
    description: 'Bitwarden 兼容的密码库服务端。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'SIGNUPS_ALLOWED', label: '允许注册', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'ADMIN_TOKEN', label: '管理后台 Token', type: 'password', generate: 'password' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'n8n',
    name: 'n8n',
    icon: '🔗',
    iconFile: 'n8n.svg',
    category: '工具',
    image: 'n8nio/n8n:latest',
    description: '可视化自动化工作流。',
    ports: [{ container: 5678, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'N8N_BASIC_AUTH_ACTIVE', label: '启用基础认证', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'N8N_BASIC_AUTH_USER', label: '用户名', type: 'text', default: 'admin' },
      { key: 'N8N_BASIC_AUTH_PASSWORD', label: '密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/home/node/.n8n'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'ubuntu-shell',
    name: 'Ubuntu 沙盒',
    icon: '📦',
    iconFile: 'ubuntu.png',
    category: '开发',
    image: 'ubuntu:24.04',
    description: '一个常驻的 Ubuntu 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'debian-shell',
    name: 'Debian 沙盒',
    icon: '🐧',
    iconFile: 'debian.png',
    category: '开发',
    image: 'debian:12',
    description: '一个常驻的 Debian 12 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'centos-shell',
    name: 'CentOS 沙盒',
    icon: '🎩',
    iconFile: 'centos.png',
    category: '开发',
    image: 'quay.io/centos/centos:stream9',
    description: '一个常驻的 CentOS Stream 9 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'httpd',
    name: 'Apache HTTP Server',
    icon: '🪶',
    iconFile: 'httpd.svg',
    category: 'Web',
    image: 'httpd:2.4-alpine',
    description: '经典 Apache，网站文件放进数据卷的 /usr/local/apache2/htdocs。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/local/apache2/htdocs'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'caddy',
    name: 'Caddy 2',
    icon: '⚡',
    iconFile: 'caddy.png',
    category: 'Web',
    image: 'caddy:2-alpine',
    description: '自带自动 HTTPS 的现代 Web 服务器，站点文件在 /usr/share/caddy，证书与状态在 /data。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/share/caddy', '/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    icon: '📝',
    iconFile: 'wordpress.svg',
    category: '建站',
    image: 'wordpress:php8.3-apache',
    description: '最流行的建站系统。需要先建一个 MySQL/MariaDB 实例，把它的容器名或 IP:端口填进下面。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'WORDPRESS_DB_HOST', label: '数据库地址（容器名或 IP:端口）', type: 'text', required: true },
      { key: 'WORDPRESS_DB_USER', label: '数据库用户', type: 'text', default: 'app', required: true },
      { key: 'WORDPRESS_DB_PASSWORD', label: '数据库密码', type: 'password', required: true },
      { key: 'WORDPRESS_DB_NAME', label: '数据库名', type: 'text', default: 'app', required: true },
    ],
    volumes: ['/var/www/html'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'halo',
    name: 'Halo 2',
    icon: '🌗',
    iconFile: 'halo.png',
    category: '建站',
    image: 'halohub/halo:2',
    description: '国产开源建站/博客系统，自带 H2 数据库，数据在 /root/.halo2。初始账号 admin。',
    ports: [{ container: 8090, protocol: 'tcp', label: 'Web' }],
    env: [
      {
        key: 'HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD',
        label: 'admin 初始密码',
        type: 'password',
        required: true,
        generate: 'password',
      },
    ],
    volumes: ['/root/.halo2'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    icon: '👻',
    iconFile: 'ghost.svg',
    category: '建站',
    image: 'ghost:5-alpine',
    description: '专注写作的博客平台，默认用 SQLite，内容在 /var/lib/ghost/content。',
    ports: [{ container: 2368, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'url', label: '站点地址（填面板给出的访问地址）', type: 'text', required: true },
    ],
    volumes: ['/var/lib/ghost/content'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    icon: '☁️',
    iconFile: 'nextcloud.svg',
    category: '建站',
    image: 'nextcloud:apache',
    description: '自建网盘 + 协作套件，默认使用 SQLite，数据在 /var/www/html。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'SQLITE_DATABASE', label: 'SQLite 库名', type: 'text', default: 'nextcloud' },
      { key: 'NEXTCLOUD_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'NEXTCLOUD_ADMIN_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
      { key: 'NEXTCLOUD_TRUSTED_DOMAINS', label: '信任域名（留空则任意）', type: 'text', default: '*' },
    ],
    volumes: ['/var/www/html'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'jupyter',
    name: 'Jupyter Notebook',
    icon: '📓',
    iconFile: 'Jupyter.png',
    category: '开发',
    image: 'quay.io/jupyter/minimal-notebook:latest',
    description: '浏览器里的 Python 笔记本，工作目录持久化在 /home/jovyan/work。',
    ports: [{ container: 8888, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'JUPYTER_TOKEN', label: '访问 Token', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/home/jovyan/work'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'python-sandbox',
    name: 'Python 沙盒',
    icon: '🐍',
    iconFile: 'python.png',
    category: '开发',
    image: 'python:3.12-slim',
    description: '常驻的 Python 3.12 容器，用「命令」页签跑脚本，代码放在 /workspace。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/workspace'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'node-sandbox',
    name: 'Node.js 沙盒',
    icon: '🟩',
    iconFile: 'nodejs.png',
    category: '开发',
    image: 'node:22-alpine',
    description: '常驻的 Node 22 容器，用「命令」页签跑 npm / node，代码放在 /workspace。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/workspace'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'go-sandbox',
    name: 'Go 沙盒',
    icon: '🐹',
    iconFile: 'go.png',
    category: '开发',
    image: 'golang:1.26-alpine',
    description:
      '常驻的 Go 1.26 容器，用「命令」页签跑 go build / go run，代码放在 /workspace，模块缓存在 /go/pkg/mod。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [
      { key: 'GOPROXY', label: '模块代理', type: 'text', default: 'https://goproxy.cn,direct' },
    ],
    volumes: ['/workspace', '/go/pkg/mod'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'openssh',
    name: 'SSH 服务器',
    icon: '🔑',
    iconFile: 'openssh.png',
    category: '开发',
    image: 'linuxserver/openssh-server:latest',
    description: '一个可以直接 SSH 登录的 Alpine 环境，配置在 /config。',
    ports: [{ container: 2222, protocol: 'tcp', label: 'SSH' }],
    env: [
      { key: 'USER_NAME', label: '登录用户名', type: 'text', default: 'dev', required: true },
      { key: 'PASSWORD_ACCESS', label: '允许密码登录', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'USER_PASSWORD', label: '登录密码', type: 'password', required: true, generate: 'password' },
      { key: 'SUDO_ACCESS', label: '允许 sudo', type: 'select', options: ['true', 'false'], default: 'false' },
    ],
    volumes: ['/config'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'verdaccio',
    name: 'Verdaccio',
    icon: '📦',
    iconFile: 'verdaccio.png',
    category: '开发',
    image: 'verdaccio/verdaccio:latest',
    description: '轻量 npm 私有仓库 / 缓存代理，包数据在 /verdaccio/storage。',
    ports: [{ container: 4873, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/verdaccio/storage'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'registry',
    name: 'Docker Registry',
    icon: '🐳',
    iconFile: 'docker.png',
    category: '开发',
    image: 'registry:2',
    description: '私有镜像仓库，镜像层存放在 /var/lib/registry。默认无鉴权，请配合内网使用。',
    ports: [{ container: 5000, protocol: 'tcp', label: 'Registry' }],
    env: [],
    volumes: ['/var/lib/registry'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'mailpit',
    name: 'Mailpit',
    icon: '📮',
    iconFile: 'mailpit.png',
    category: '开发',
    image: 'axllent/mailpit:latest',
    description: '开发用邮件捕获器：应用把邮件发到它的 SMTP，网页上就能看到。',
    ports: [
      { container: 8025, protocol: 'tcp', label: 'Web' },
      { container: 1025, protocol: 'tcp', label: 'SMTP' },
    ],
    env: [{ key: 'MP_DATABASE', label: '持久化文件', type: 'text', default: '/data/mailpit.db' }],
    volumes: ['/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'mariadb',
    name: 'MariaDB 11',
    icon: '🦭',
    iconFile: 'mariadb.png',
    category: '数据库',
    image: 'mariadb:11',
    description: 'MySQL 的社区分支，数据持久化在 /var/lib/mysql。',
    ports: [{ container: 3306, protocol: 'tcp', label: 'MariaDB' }],
    env: [
      { key: 'MARIADB_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
      { key: 'MARIADB_DATABASE', label: '默认数据库', type: 'text', default: 'app' },
      { key: 'MARIADB_USER', label: '普通用户', type: 'text', default: 'app' },
      { key: 'MARIADB_PASSWORD', label: '普通用户密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/var/lib/mysql'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    icon: '🐇',
    iconFile: 'rabbitmq.png',
    category: '数据库',
    image: 'rabbitmq:3-management-alpine',
    description: '消息队列，带管理后台（15672）。数据在 /var/lib/rabbitmq。',
    ports: [
      { container: 5672, protocol: 'tcp', label: 'AMQP' },
      { container: 15672, protocol: 'tcp', label: '管理后台' },
    ],
    env: [
      { key: 'RABBITMQ_DEFAULT_USER', label: '用户名', type: 'text', default: 'admin', required: true },
      { key: 'RABBITMQ_DEFAULT_PASS', label: '密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/var/lib/rabbitmq'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'influxdb',
    name: 'InfluxDB 2',
    icon: '📉',
    iconFile: 'influxdb.png',
    category: '数据库',
    image: 'influxdb:2',
    description: '时序数据库，首次启动自动完成初始化，数据在 /var/lib/influxdb2。',
    ports: [{ container: 8086, protocol: 'tcp', label: 'HTTP API' }],
    env: [
      { key: 'DOCKER_INFLUXDB_INIT_MODE', label: '初始化模式', type: 'select', options: ['setup'], default: 'setup', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_USERNAME', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_PASSWORD', label: '管理员密码（≥8 位）', type: 'password', required: true, generate: 'password' },
      { key: 'DOCKER_INFLUXDB_INIT_ORG', label: '组织', type: 'text', default: 'my-org', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_BUCKET', label: '默认 bucket', type: 'text', default: 'default', required: true },
    ],
    volumes: ['/var/lib/influxdb2'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    icon: '🏎️',
    iconFile: 'clickhouse.png',
    category: '数据库',
    image: 'clickhouse/clickhouse-server:latest',
    description: '列式 OLAP 数据库，HTTP 接口在 8123，数据在 /var/lib/clickhouse。',
    ports: [{ container: 8123, protocol: 'tcp', label: 'HTTP' }],
    env: [
      { key: 'CLICKHOUSE_USER', label: '用户名', type: 'text', default: 'app', required: true },
      { key: 'CLICKHOUSE_PASSWORD', label: '密码', type: 'password', required: true, generate: 'password' },
      { key: 'CLICKHOUSE_DB', label: '默认数据库', type: 'text', default: 'app' },
    ],
    volumes: ['/var/lib/clickhouse'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'memcached',
    name: 'Memcached',
    icon: '🧠',
    iconFile: 'memcached.svg',
    category: '数据库',
    image: 'memcached:alpine',
    description: '纯内存缓存，没有持久化，重启即清空。',
    ports: [{ container: 11211, protocol: 'tcp', label: 'Memcached' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'meilisearch',
    name: 'Meilisearch',
    icon: '🔎',
    iconFile: 'meilisearch.png',
    category: '数据库',
    image: 'getmeili/meilisearch:latest',
    description: '开箱即用的全文搜索引擎，索引数据在 /meili_data。',
    ports: [{ container: 7700, protocol: 'tcp', label: 'HTTP API' }],
    env: [
      { key: 'MEILI_MASTER_KEY', label: 'Master Key（≥16 位）', type: 'password', required: true, generate: 'password' },
      { key: 'MEILI_ENV', label: '运行模式', type: 'select', options: ['production', 'development'], default: 'production' },
    ],
    volumes: ['/meili_data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'adminer',
    name: 'Adminer',
    icon: '🗃️',
    iconFile: 'adminer.svg',
    category: '工具',
    image: 'adminer:latest',
    description: '单文件数据库管理界面，支持 MySQL / PostgreSQL / SQLite 等，无需持久化。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'filebrowser',
    name: 'File Browser',
    icon: '📂',
    iconFile: 'filebrowser.svg',
    category: '工具',
    image: 'filebrowser/filebrowser:s6',
    description: '网页版文件管理器，文件放在 /srv，配置库在 /database。初始账号 admin/admin，登录后请立刻改密。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/srv', '/database'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'syncthing',
    name: 'Syncthing',
    icon: '🔄',
    iconFile: 'syncthing.svg',
    category: '工具',
    image: 'syncthing/syncthing:latest',
    description: '点对点文件同步，配置与同步目录都在 /var/syncthing。',
    ports: [
      { container: 8384, protocol: 'tcp', label: 'Web' },
      { container: 22000, protocol: 'tcp', label: '同步' },
    ],
    env: [],
    volumes: ['/var/syncthing'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'it-tools',
    name: 'IT Tools',
    icon: '🧰',
    iconFile: 'it-tools.svg',
    category: '工具',
    image: 'corentinth/it-tools:latest',
    description: '一堆开发常用小工具（编解码、格式化、生成器）的合集网页，无需持久化。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'stirling-pdf',
    name: 'Stirling PDF',
    icon: '📄',
    iconFile: 'stirling-pdf.svg',
    category: '工具',
    image: 'stirlingtools/stirling-pdf:latest',
    description: '本地跑的 PDF 全能工具箱：合并、拆分、压缩、OCR。配置在 /configs。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/configs'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'memos',
    name: 'Memos',
    icon: '🗒️',
    iconFile: 'memos.png',
    category: '工具',
    image: 'neosmemo/memos:stable',
    description: '轻量自建笔记 / 想法流，数据在 /var/opt/memos。',
    ports: [{ container: 5230, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/opt/memos'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'grafana',
    name: 'Grafana',
    icon: '📊',
    iconFile: 'grafana.svg',
    category: '工具',
    image: 'grafana/grafana:latest',
    description: '数据可视化与仪表盘，仪表盘数据在 /var/lib/grafana。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'GF_SECURITY_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'GF_SECURITY_ADMIN_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/var/lib/grafana'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    icon: '🔍',
    iconFile: 'searxng.svg',
    category: '工具',
    image: 'searxng/searxng:latest',
    description: '自建聚合搜索引擎，不记录隐私。配置在 /etc/searxng，首次启动自动生成。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'SEARXNG_BASE_URL', label: '站点地址（填面板给出的访问地址）', type: 'text' }],
    volumes: ['/etc/searxng'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'freshrss',
    name: 'FreshRSS',
    icon: '📰',
    iconFile: 'freshrss.svg',
    category: '工具',
    image: 'freshrss/freshrss:latest',
    description: '自建 RSS 阅读器，数据在 /var/www/FreshRSS/data。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/www/FreshRSS/data', '/var/www/FreshRSS/extensions'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'nocodb',
    name: 'NocoDB',
    icon: '🧮',
    iconFile: 'nocodb.svg',
    category: '工具',
    image: 'nocodb/nocodb:latest',
    description: '把数据库变成 Airtable 那样的表格界面，自带 SQLite，数据在 /usr/app/data。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/usr/app/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'homer',
    name: 'Homer',
    icon: '🏠',
    iconFile: 'homer.svg',
    category: '工具',
    image: 'b4bz/homer:latest',
    description: '静态服务导航页，编辑数据卷里 /www/assets/config.yml 就能改。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/www/assets'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    icon: '🌀',
    iconFile: 'qbittorrent.svg',
    category: '工具',
    image: 'linuxserver/qbittorrent:latest',
    description: '带网页界面的 BT 客户端，下载目录 /downloads，配置 /config。首次登录用户名 admin，密码见容器日志。',
    ports: [
      { container: 8080, protocol: 'tcp', label: 'Web' },
      { container: 6881, protocol: 'tcp', label: 'BT' },
    ],
    env: [
      { key: 'WEBUI_PORT', label: 'Web 端口', type: 'text', default: '8080', required: true },
      { key: 'PUID', label: 'UID', type: 'text', default: '1000' },
      { key: 'PGID', label: 'GID', type: 'text', default: '1000' },
    ],
    volumes: ['/config', '/downloads'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    icon: '🎬',
    iconFile: 'jellyfin.svg',
    category: '媒体',
    image: 'jellyfin/jellyfin:latest',
    description: '开源影音媒体库，把片子放进数据卷的 /media，配置在 /config。',
    ports: [{ container: 8096, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config', '/media'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    icon: '🎵',
    iconFile: 'navidrome.svg',
    category: '媒体',
    image: 'deluan/navidrome:latest',
    description: '自建音乐流媒体，兼容 Subsonic 客户端。音乐放 /music，索引在 /data。',
    ports: [{ container: 4533, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'ND_LOGLEVEL', label: '日志级别', type: 'select', options: ['error', 'info', 'debug'], default: 'info' }],
    volumes: ['/data', '/music'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    icon: '🖼️',
    iconFile: 'photoprism.svg',
    category: '媒体',
    image: 'photoprism/photoprism:latest',
    description: 'AI 相册管理，原图放 /photoprism/originals，索引与缩略图在 /photoprism/storage。',
    ports: [{ container: 2342, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'PHOTOPRISM_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'PHOTOPRISM_ADMIN_PASSWORD', label: '管理员密码（≥8 位）', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/photoprism/storage', '/photoprism/originals'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'open-webui',
    name: 'Open WebUI',
    icon: '💬',
    iconFile: 'open-webui.svg',
    category: 'AI',
    image: 'ghcr.io/open-webui/open-webui:main',
    description: '类 ChatGPT 的自托管前端，可接 Ollama 或任意 OpenAI 兼容接口，数据在 /app/backend/data。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'WEBUI_SECRET_KEY', label: '会话密钥', type: 'password', required: true, generate: 'password' },
      { key: 'OPENAI_API_BASE_URL', label: 'OpenAI 兼容接口地址', type: 'text', default: 'https://api.openai.com/v1' },
      { key: 'OPENAI_API_KEY', label: 'API Key（可留空）', type: 'password' },
    ],
    volumes: ['/app/backend/data'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    iconFile: 'ollama.svg',
    category: 'AI',
    image: 'ollama/ollama:latest',
    description: '本地大模型运行时（纯 CPU 推理较慢），模型权重存在 /root/.ollama，用「命令」页签 ollama pull 拉模型。',
    ports: [{ container: 11434, protocol: 'tcp', label: 'API' }],
    env: [],
    volumes: ['/root/.ollama'],
    defaults: { memoryMb: 4096, cpus: 4 },
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    icon: '🦞',
    iconFile: 'openclaw.svg',
    category: 'AI',
    image: 'openclaw/openclaw:latest',
    description: '跑在自己设备上的个人 AI 助手网关：接任意模型（OpenAI / Anthropic / 本地模型），从 Telegram、WhatsApp、Discord 等渠道收发消息。首次启动后打开 18789 的网页控制台完成初始化。',
    cmd: ['node', 'dist/index.js', 'gateway', '--bind', 'lan', '--port', '18789'],
    ports: [{ container: 18789, protocol: 'tcp', label: '控制台' }],
    env: [
      { key: 'OPENCLAW_GATEWAY_TOKEN', label: '网关 Token（控制台登录用）', type: 'password', generate: 'password' },
    ],
    volumes: ['/home/node/.openclaw', '/home/node/.config/openclaw'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'hermes',
    name: 'Hermes Agent',
    icon: '☤',
    iconFile: 'hermes.svg',
    category: 'AI',
    image: 'nousresearch/hermes-agent:latest',
    description: 'Nous Research 的自进化 AI 代理：技能从经验中自学、跨会话记忆，从 Telegram / Discord / Slack / WhatsApp 收发消息。网关只主动外连、无入站端口；配置请用「控制台」跑 hermes setup，或直接编辑数据卷里的 hermes.json。',
    cmd: ['gateway', 'run'],
    ports: [],
    env: [],
    volumes: ['/opt/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'minecraft-bedrock',
    name: 'Minecraft 基岩版服务器',
    icon: '🧱',
    iconFile: 'minecraft-bedrock.png',
    category: '游戏',
    image: 'itzg/minecraft-bedrock-server:latest',
    description: '手机 / 主机 / Win10 版能进的基岩版服务端，存档在 /data。UDP 服务不支持闲时休眠。',
    ports: [{ container: 19132, protocol: 'udp', label: 'Bedrock' }],
    env: [
      { key: 'EULA', label: '同意 EULA', type: 'select', options: ['TRUE'], default: 'TRUE', required: true },
      { key: 'VERSION', label: '版本', type: 'text', default: 'LATEST' },
      { key: 'SERVER_NAME', label: '服务器名', type: 'text', default: 'Bedrock Server' },
      { key: 'GAMEMODE', label: '游戏模式', type: 'select', options: ['survival', 'creative', 'adventure'], default: 'survival' },
      { key: 'DIFFICULTY', label: '难度', type: 'select', options: ['peaceful', 'easy', 'normal', 'hard'], default: 'easy' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'factorio',
    name: 'Factorio 服务器',
    icon: '🏭',
    iconFile: 'factorio.svg',
    category: '游戏',
    image: 'factoriotools/factorio:stable',
    description: '异星工厂多人服务端，存档与配置在 /factorio。UDP 服务不支持闲时休眠。',
    ports: [{ container: 34197, protocol: 'udp', label: 'Factorio' }],
    env: [],
    volumes: ['/factorio'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'valheim',
    name: 'Valheim 服务器',
    icon: '🛡️',
    iconFile: 'valheim.svg',
    category: '游戏',
    image: 'lloesche/valheim-server:latest',
    description: '英灵神殿专用服务端，存档在 /config。首次启动要下载几 GB，UDP 服务不支持闲时休眠。',
    ports: [
      { container: 2456, protocol: 'udp', label: '游戏' },
      { container: 2457, protocol: 'udp', label: '查询' },
    ],
    env: [
      { key: 'SERVER_NAME', label: '服务器名', type: 'text', default: 'Valheim', required: true },
      { key: 'WORLD_NAME', label: '世界名', type: 'text', default: 'Dedicated', required: true },
      { key: 'SERVER_PASS', label: '进服密码（≥5 位）', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/config'],
    defaults: { memoryMb: 4096, cpus: 2 },
  },
  {
    id: 'minio',
    name: 'MinIO',
    icon: '🪣',
    iconFile: 'minio.svg',
    category: '工具',
    image: 'minio/minio:latest',
    description: '兼容 S3 API 的对象存储，带管理控制台。对象数据持久化在 /data。',
    cmd: ['server', '/data', '--console-address', ':9001'],
    ports: [
      { container: 9000, protocol: 'tcp', label: 'S3 API' },
      { container: 9001, protocol: 'tcp', label: '控制台' },
    ],
    env: [
      { key: 'MINIO_ROOT_USER', label: '管理员用户名', type: 'text', default: 'minioadmin', required: true },
      { key: 'MINIO_ROOT_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'gotify',
    name: 'Gotify',
    icon: '🔔',
    iconFile: 'gotify.svg',
    category: '工具',
    image: 'gotify/server:latest',
    description: '自建推送通知服务器，可让脚本和应用向手机或浏览器发送消息。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'GOTIFY_DEFAULTUSER_PASS', label: '管理员密码', type: 'password', required: true, generate: 'password' }],
    volumes: ['/app/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'ntfy',
    name: 'ntfy',
    icon: '📣',
    iconFile: 'ntfy.svg',
    category: '工具',
    image: 'binwiederhier/ntfy:latest',
    description: '轻量的发布订阅通知服务，通过主题 URL 接收和推送消息。',
    cmd: ['serve'],
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/cache/ntfy', '/etc/ntfy'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'changedetection',
    name: 'changedetection.io',
    icon: '👁️',
    iconFile: 'changedetection.svg',
    category: '工具',
    image: 'dgtlmoon/changedetection.io:latest',
    description: '监控网页内容变化，发现更新时通过通知渠道提醒。',
    ports: [{ container: 5000, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/datastore'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'privatebin',
    name: 'PrivateBin',
    icon: '🗒️',
    iconFile: 'privatebin.svg',
    category: '工具',
    image: 'privatebin/nginx-fpm-alpine:latest',
    description: '端到端加密的文本分享服务，适合临时分享密码、代码和笔记。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/srv/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'actual-budget',
    name: 'Actual Budget',
    icon: '💸',
    iconFile: 'actual-budget.svg',
    category: '工具',
    image: 'actualbudget/actual-server:latest',
    description: '以本地优先为核心的个人预算管理服务，数据持久化在 /data。',
    ports: [{ container: 5006, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'vikunja',
    name: 'Vikunja',
    icon: '✅',
    iconFile: 'vikunja.svg',
    category: '工具',
    image: 'vikunja/vikunja:latest',
    description: '开源待办和项目管理服务，默认使用 SQLite，数据持久化在 /app/vikunja。',
    ports: [{ container: 3456, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/vikunja'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'flame',
    name: 'Flame',
    icon: '🔥',
    iconFile: 'flame.svg',
    category: '工具',
    image: 'pawelmalak/flame:latest',
    description: '简洁的自托管服务导航页，可收藏常用链接和应用。',
    ports: [{ container: 5005, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    icon: '🏠',
    iconFile: 'home-assistant.svg',
    category: '工具',
    image: 'ghcr.io/home-assistant/home-assistant:stable',
    description: '开源智能家居中枢，自动发现和整合设备，配置持久化在 /config。',
    ports: [{ container: 8123, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    icon: '✏️',
    iconFile: 'excalidraw.svg',
    category: '工具',
    image: 'excalidraw/excalidraw:latest',
    description: '手绘风格的在线白板，适合快速画流程图、草图和协作笔记。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'drawio',
    name: 'draw.io',
    icon: '📐',
    iconFile: 'drawio.svg',
    category: '工具',
    image: 'jgraph/drawio:latest',
    description: '功能完整的流程图和架构图编辑器，可直接在浏览器中使用。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'cyberchef',
    name: 'CyberChef',
    icon: '🧑‍🍳',
    iconFile: 'cyberchef.svg',
    category: '开发',
    image: 'mpepping/cyberchef:latest',
    description: '浏览器里的数据处理工具箱，支持编码、解码、加密、格式转换等操作。',
    ports: [{ container: 8000, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'plantuml',
    name: 'PlantUML Server',
    icon: '🌱',
    iconFile: 'plantuml.svg',
    category: '开发',
    image: 'plantuml/plantuml-server:jetty',
    description: '根据文本生成 UML 图和架构图，适合接入文档和开发工作流。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'portainer',
    name: 'Portainer CE',
    icon: '🐳',
    iconFile: 'portainer.svg',
    category: '工具',
    image: 'portainer/portainer-ce:latest',
    description: 'Docker 图形化管理面板，管理镜像、容器、网络和数据卷。',
    ports: [{ container: 9000, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'dozzle',
    name: 'Dozzle',
    icon: '📜',
    iconFile: 'dozzle.svg',
    category: '工具',
    image: 'amir20/dozzle:latest',
    description: '轻量 Docker 容器日志查看器，适合快速查看运行状态和实时日志。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'adguard-home',
    name: 'AdGuard Home',
    icon: '🛡️',
    iconFile: 'adguard-home.svg',
    category: '工具',
    image: 'adguard/adguardhome:latest',
    description: '全网 DNS 广告拦截和家庭网络管理，配置与过滤规则持久化保存。',
    ports: [{ container: 3000, protocol: 'tcp', label: '初始化/Web' }],
    env: [],
    volumes: ['/opt/adguardhome/work', '/opt/adguardhome/conf'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'pihole',
    name: 'Pi-hole',
    icon: '🕳️',
    iconFile: 'pihole.svg',
    category: '工具',
    image: 'pihole/pihole:latest',
    description: '网络级 DNS 广告拦截器和本地 DNS 管理面板。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'FTLCONF_webserver_api_password', label: '管理后台密码', type: 'password', generate: 'password' }],
    volumes: ['/etc/pihole', '/etc/dnsmasq.d'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'forgejo',
    name: 'Forgejo',
    icon: '🦊',
    iconFile: 'forgejo.svg',
    category: '开发',
    image: 'codeberg.org/forgejo/forgejo:latest',
    description: '轻量自托管 Git 服务，支持代码仓库、Issue、Actions 和包管理。',
    ports: [
      { container: 3000, protocol: 'tcp', label: 'Web' },
      { container: 22, protocol: 'tcp', label: 'SSH' },
    ],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'pgadmin',
    name: 'pgAdmin 4',
    icon: '🐘',
    iconFile: 'pgadmin.svg',
    category: '数据库',
    image: 'dpage/pgadmin4:latest',
    description: 'PostgreSQL 图形化管理工具，可连接面板中的 PostgreSQL 实例。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'PGADMIN_DEFAULT_EMAIL', label: '登录邮箱', type: 'text', default: 'admin@example.com', required: true },
      { key: 'PGADMIN_DEFAULT_PASSWORD', label: '登录密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/var/lib/pgadmin'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'phpmyadmin',
    name: 'phpMyAdmin',
    icon: '🗄️',
    iconFile: 'phpmyadmin.svg',
    category: '数据库',
    image: 'phpmyadmin:latest',
    description: 'MySQL / MariaDB 图形化管理工具，连接已有数据库实例使用。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'PMA_ARBITRARY', label: '允许输入任意数据库地址', type: 'select', options: ['1'], default: '1' }],
    volumes: [],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'sftpgo',
    name: 'SFTPGo',
    icon: '📤',
    iconFile: 'sftpgo.svg',
    category: '工具',
    image: 'drakkan/sftpgo:latest',
    description: '支持 SFTP、FTP、WebDAV 和 HTTP 的文件传输服务器，带管理面板。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/lib/sftpgo'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'owncast',
    name: 'Owncast',
    icon: '📺',
    iconFile: 'owncast.svg',
    category: '媒体',
    image: 'owncast/owncast:latest',
    description: '个人直播和视频流服务器，支持 RTMP 推流和网页播放。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'linkding',
    name: 'Linkding',
    icon: '🔖',
    iconFile: 'linkding.svg',
    category: '工具',
    image: 'sissbruecker/linkding:latest',
    description: '极简自托管书签服务，支持标签、搜索和浏览器扩展。',
    ports: [{ container: 9090, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/etc/linkding/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'glances',
    name: 'Glances',
    icon: '📈',
    iconFile: 'glances.svg',
    category: '工具',
    image: 'nicolargo/glances:latest-full',
    cmd: ['glances', '-w'],
    description: '实时系统资源监控面板，展示 CPU、内存、磁盘、网络和进程。',
    ports: [{ container: 61208, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'traefik',
    name: 'Traefik',
    icon: '🚦',
    iconFile: 'traefik.svg',
    category: 'Web',
    image: 'traefik:v3.3',
    description: '现代反向代理和入口控制器，提供路由、TLS 和中间件能力。',
    cmd: ['--api.insecure=true', '--entrypoints.web.address=:80'],
    ports: [
      { container: 80, protocol: 'tcp', label: 'HTTP' },
      { container: 8080, protocol: 'tcp', label: 'Dashboard' },
    ],
    env: [],
    volumes: [],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    icon: '🔥',
    iconFile: 'prometheus.svg',
    category: '工具',
    image: 'prom/prometheus:latest',
    description: '时间序列监控和告警平台，适合收集应用与主机指标。',
    ports: [{ container: 9090, protocol: 'tcp', label: 'Web/API' }],
    env: [],
    volumes: ['/prometheus'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'netdata',
    name: 'Netdata',
    icon: '📉',
    iconFile: 'netdata.svg',
    category: '工具',
    image: 'netdata/netdata:latest',
    description: '实时主机和容器监控面板，开箱即用地展示大量性能指标。',
    ports: [{ container: 19999, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/etc/netdata', '/var/lib/netdata', '/var/cache/netdata'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'alertmanager',
    name: 'Alertmanager',
    icon: '🔔',
    iconFile: 'alertmanager.svg',
    category: '工具',
    image: 'prom/alertmanager:latest',
    description: 'Prometheus 告警分组、静默和通知分发组件。',
    ports: [{ container: 9093, protocol: 'tcp', label: 'Web/API' }],
    env: [],
    volumes: ['/alertmanager'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'duplicati',
    name: 'Duplicati',
    icon: '💾',
    iconFile: 'duplicati.svg',
    category: '工具',
    image: 'duplicati/duplicati:latest',
    description: '支持云存储和加密的增量备份工具，带浏览器管理界面。',
    ports: [{ container: 8200, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/data', '/backups', '/source'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'paperless-ngx',
    name: 'Paperless-ngx',
    icon: '🗂️',
    iconFile: 'paperless-ngx.svg',
    category: '工具',
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest',
    description: '扫描件和电子文档管理系统，支持 OCR、标签和全文搜索。',
    ports: [{ container: 8000, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'PAPERLESS_SECRET_KEY', label: '应用密钥', type: 'password', required: true, generate: 'password' },
      { key: 'PAPERLESS_TIME_ZONE', label: '时区', type: 'text', default: 'Asia/Shanghai' },
    ],
    volumes: ['/usr/src/paperless/data', '/usr/src/paperless/media', '/usr/src/paperless/export', '/usr/src/paperless/consume'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'mealie',
    name: 'Mealie',
    icon: '🍲',
    iconFile: 'mealie.svg',
    category: '工具',
    image: 'ghcr.io/mealie-recipes/mealie:latest',
    description: '自托管菜谱和膳食计划管理，支持从网页导入菜谱。',
    ports: [{ container: 9000, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'BASE_URL', label: '站点地址', type: 'text', default: 'http://localhost:9000' },
      { key: 'ALLOW_SIGNUP', label: '允许注册', type: 'select', options: ['true', 'false'], default: 'true' },
    ],
    volumes: ['/app/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'homebox',
    name: 'HomeBox',
    icon: '📦',
    iconFile: 'homebox.svg',
    category: '工具',
    image: 'ghcr.io/sysadminsmedia/homebox:latest',
    description: '家庭物品和资产清单，记录位置、购买信息和保修期。',
    ports: [{ container: 7745, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'jellyseerr',
    name: 'Jellyseerr',
    icon: '🎞️',
    iconFile: 'jellyseerr.svg',
    category: '媒体',
    image: 'fallenbagel/jellyseerr:latest',
    description: 'Jellyfin 媒体库的影视请求和发现界面，可对接自动下载工具。',
    ports: [{ container: 5055, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/config'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    icon: '🎧',
    iconFile: 'audiobookshelf.svg',
    category: '媒体',
    image: 'ghcr.io/advplyr/audiobookshelf:latest',
    description: '有声书和播客媒体库，支持进度同步和多用户。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config', '/metadata', '/audiobooks', '/podcasts'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'calibre-web',
    name: 'Calibre-Web',
    icon: '📚',
    iconFile: 'calibre-web.svg',
    category: '媒体',
    image: 'linuxserver/calibre-web:latest',
    description: '电子书图书馆和阅读器，支持 OPDS、用户管理和浏览器阅读。',
    ports: [{ container: 8083, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config', '/books'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'komga',
    name: 'Komga',
    icon: '📖',
    iconFile: 'komga.svg',
    category: '媒体',
    image: 'gotson/komga:latest',
    description: '漫画、电子书和杂志媒体库，支持阅读进度与多用户。',
    ports: [{ container: 25600, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config', '/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'nginx-proxy-manager',
    name: 'Nginx Proxy Manager',
    icon: '🔀',
    iconFile: 'nginx-proxy-manager.svg',
    category: 'Web',
    image: 'jc21/nginx-proxy-manager:latest',
    description: '带图形界面的反向代理和证书管理工具，适合管理多个域名和 HTTPS。',
    ports: [
      { container: 81, protocol: 'tcp', label: '管理面板' },
      { container: 80, protocol: 'tcp', label: 'HTTP' },
      { container: 443, protocol: 'tcp', label: 'HTTPS' },
    ],
    env: [],
    volumes: ['/data', '/etc/letsencrypt'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'radicale',
    name: 'Radicale',
    icon: '📅',
    iconFile: 'radicale.svg',
    category: '工具',
    image: 'tomsquest/docker-radicale:latest',
    description: '轻量 CalDAV/CardDAV 服务，可同步日历和联系人。',
    ports: [{ container: 5232, protocol: 'tcp', label: 'WebDAV' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'librespeed',
    name: 'LibreSpeed',
    icon: '⚡',
    iconFile: 'librespeed.svg',
    category: '工具',
    image: 'linuxserver/librespeed:latest',
    description: '无广告的自托管网络测速页面，测试下载、上传和延迟。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'rss-bridge',
    name: 'RSS-Bridge',
    icon: '📡',
    iconFile: 'rss-bridge.svg',
    category: '工具',
    image: 'rssbridge/rss-bridge:latest',
    description: '将缺少 RSS 的网站和社交平台转换为可订阅的 RSS 源。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'gotenberg',
    name: 'Gotenberg',
    icon: '📄',
    iconFile: 'gotenberg.svg',
    category: '开发',
    image: 'gotenberg/gotenberg:8',
    description: '文档和网页转 PDF 的 HTTP API，适合接入应用自动生成报表。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'API' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'webtop',
    name: 'Webtop',
    icon: '🖥️',
    iconFile: 'webtop.svg',
    category: '开发',
    image: 'linuxserver/webtop:ubuntu-xfce',
    description: '浏览器中的完整 Ubuntu 桌面，适合轻量图形化开发和远程工作。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'Web Desktop' }],
    env: [],
    volumes: ['/config'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'cloudcmd',
    name: 'Cloud Commander',
    icon: '🗂️',
    iconFile: 'cloudcmd.svg',
    category: '开发',
    image: 'coderaiser/cloudcmd:latest',
    description: '网页文件管理器和命令行终端，方便管理容器数据卷中的文件。',
    ports: [{ container: 8000, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'browserless',
    name: 'Browserless',
    icon: '🌐',
    iconFile: 'browserless.svg',
    category: '开发',
    image: 'browserless/chrome:latest',
    description: '托管 Headless Chrome，供爬虫、截图、PDF 和自动化任务通过 API 调用。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'API' }],
    env: [{ key: 'TOKEN', label: 'API Token', type: 'password', required: true, generate: 'password' }],
    volumes: [],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'swagger-ui',
    name: 'Swagger UI',
    icon: '📘',
    iconFile: 'swagger-ui.svg',
    category: '开发',
    image: 'swaggerapi/swagger-ui:latest',
    description: '在浏览器中浏览、调试和分享 OpenAPI 接口文档。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'URL', label: 'OpenAPI 文档地址', type: 'text', default: 'https://petstore.swagger.io/v2/swagger.json' }],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'new-api',
    name: 'New API',
    icon: '🍥',
    iconFile: 'new-api.png',
    category: 'AI',
    image: 'calciumion/new-api:latest',
    description: '统一管理和分发多个大模型 API 的网关，默认使用 SQLite 保存数据。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'Web/API' }],
    env: [
      { key: 'TZ', label: '时区', type: 'text', default: 'Asia/Shanghai' },
      { key: 'SESSION_SECRET', label: '会话密钥', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'sub2api',
    name: 'Sub2API',
    icon: '🔁',
    iconFile: 'sub2api.svg',
    category: 'AI',
    image: 'weishaw/sub2api:latest',
    description: '多模型订阅中转与账号管理服务。需先创建 PostgreSQL 和 Redis 实例，并填写它们在共享 Docker 网络中的容器地址。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web/API' }],
    env: [
      { key: 'AUTO_SETUP', label: '自动初始化', type: 'select', options: ['true'], default: 'true', required: true },
      { key: 'DATABASE_HOST', label: 'PostgreSQL 容器地址', type: 'text', required: true },
      { key: 'DATABASE_PORT', label: 'PostgreSQL 端口', type: 'text', default: '5432', required: true },
      { key: 'DATABASE_USER', label: 'PostgreSQL 用户名', type: 'text', required: true },
      { key: 'DATABASE_PASSWORD', label: 'PostgreSQL 密码', type: 'password', required: true },
      { key: 'DATABASE_DBNAME', label: 'PostgreSQL 数据库名', type: 'text', required: true },
      { key: 'REDIS_HOST', label: 'Redis 容器地址', type: 'text', required: true },
      { key: 'REDIS_PORT', label: 'Redis 端口', type: 'text', default: '6379', required: true },
      { key: 'REDIS_PASSWORD', label: 'Redis 密码（没有则留空）', type: 'password' },
      { key: 'ADMIN_EMAIL', label: '管理员邮箱', type: 'text', default: 'admin@sub2api.local', required: true },
      { key: 'ADMIN_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
      { key: 'JWT_SECRET', label: 'JWT 密钥', type: 'password', required: true, generate: 'password' },
      { key: 'TOTP_ENCRYPTION_KEY', label: '二次验证加密密钥', type: 'password', required: true, generate: 'password' },
      { key: 'TZ', label: '时区', type: 'text', default: 'Asia/Shanghai' },
    ],
    volumes: ['/app/data'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'astrbot',
    name: 'AstrBot',
    icon: '🤖',
    iconFile: 'astrbot.png',
    category: 'AI',
    image: 'soulter/astrbot:latest',
    description: '接入 QQ、Telegram、Discord 等平台的大模型机器人与 Agent 平台，支持插件和 WebUI。',
    ports: [
      { container: 6185, protocol: 'tcp', label: '管理 WebUI' },
      { container: 6199, protocol: 'tcp', label: 'Web Chat/API' },
    ],
    env: [],
    volumes: ['/AstrBot/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'napcat',
    name: 'NapCat',
    icon: '🐱',
    iconFile: 'napcat.png',
    category: 'AI',
    image: 'mlikiowa/napcat-docker:latest',
    description: '基于 QQ 的 OneBot 协议实现，可作为 AstrBot 等机器人的 QQ 消息端。请勿将管理端口直接暴露到公网。',
    ports: [
      { container: 6099, protocol: 'tcp', label: 'NapCat WebUI' },
      { container: 3000, protocol: 'tcp', label: 'QQ Web' },
      { container: 3001, protocol: 'tcp', label: 'QQ 辅助端口' },
    ],
    env: [
      { key: 'NAPCAT_UID', label: '容器用户 UID（可留空）', type: 'text' },
      { key: 'NAPCAT_GID', label: '容器用户 GID（可留空）', type: 'text' },
    ],
    volumes: ['/app/.config/QQ', '/app/napcat/config', '/app/napcat/plugins'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'openlist',
    name: 'OpenList',
    icon: '📂',
    iconFile: 'openlist.svg',
    category: '工具',
    image: 'openlistteam/openlist:latest',
    description: '多存储挂载与文件索引服务，支持网盘、对象存储和 WebDAV。首次启动后从管理面板设置账号。',
    ports: [
      { container: 5244, protocol: 'tcp', label: 'Web/API' },
      { container: 5245, protocol: 'tcp', label: 'HTTPS' },
    ],
    env: [
      { key: 'TZ', label: '时区', type: 'text', default: 'Asia/Shanghai' },
      { key: 'UMASK', label: '文件权限掩码', type: 'text', default: '022' },
    ],
    volumes: ['/opt/openlist/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
];

export const templateById = (id) => TEMPLATES.find((t) => t.id === id) || null;

/** Strips nothing today, but keeps a single place to control what the client sees. */
export const publicTemplates = () => TEMPLATES;
