/**
 * Image catalog. Everything a normal user can deploy without the
 * `allow_custom_image` flag comes from here.
 *
 * env[].generate = 'password' -> a random value is generated when the user
 * leaves the field empty, and shown back on the instance page.
 */
export const TEMPLATES = [
  {
    id: 'nginx',
    name: 'Nginx',
    icon: '🌐',
    category: 'Web',
    image: 'nginx:alpine',
    description: '静态网站 / 反向代理。把文件放进数据卷的 /usr/share/nginx/html 即可。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/share/nginx/html'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'code-server',
    name: 'code-server (VS Code)',
    icon: '🧑‍💻',
    category: '开发',
    image: 'codercom/code-server:latest',
    description: '浏览器里的 VS Code，工作目录持久化在 /home/coder/project。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web IDE' }],
    env: [
      { key: 'PASSWORD', label: '访问密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/home/coder/project'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'postgres',
    name: 'PostgreSQL 16',
    icon: '🐘',
    category: '数据库',
    image: 'postgres:16-alpine',
    description: '关系型数据库，数据持久化在 /var/lib/postgresql/data。',
    ports: [{ container: 5432, protocol: 'tcp', label: 'Postgres' }],
    env: [
      { key: 'POSTGRES_USER', label: '用户名', type: 'text', default: 'app', required: true },
      { key: 'POSTGRES_PASSWORD', label: '密码', type: 'password', required: true, generate: 'password' },
      { key: 'POSTGRES_DB', label: '默认数据库', type: 'text', default: 'app' },
    ],
    volumes: ['/var/lib/postgresql/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'mysql',
    name: 'MySQL 8',
    icon: '🐬',
    category: '数据库',
    image: 'mysql:8',
    description: '经典 MySQL，数据持久化在 /var/lib/mysql。',
    ports: [{ container: 3306, protocol: 'tcp', label: 'MySQL' }],
    env: [
      { key: 'MYSQL_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
      { key: 'MYSQL_DATABASE', label: '默认数据库', type: 'text', default: 'app' },
      { key: 'MYSQL_USER', label: '普通用户', type: 'text', default: 'app' },
      { key: 'MYSQL_PASSWORD', label: '普通用户密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/var/lib/mysql'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'redis',
    name: 'Redis 7',
    icon: '🔴',
    category: '数据库',
    image: 'redis:7-alpine',
    description: '内存 KV，开启 AOF 持久化到 /data。',
    cmd: ['redis-server', '--appendonly', 'yes'],
    ports: [{ container: 6379, protocol: 'tcp', label: 'Redis' }],
    env: [],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'mongo',
    name: 'MongoDB 7',
    icon: '🍃',
    category: '数据库',
    image: 'mongo:7',
    description: '文档数据库，数据在 /data/db。',
    ports: [{ container: 27017, protocol: 'tcp', label: 'MongoDB' }],
    env: [
      { key: 'MONGO_INITDB_ROOT_USERNAME', label: 'root 用户', type: 'text', default: 'root', required: true },
      { key: 'MONGO_INITDB_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/data/db'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'minecraft',
    name: 'Minecraft Java 服务器',
    icon: '⛏️',
    category: '游戏',
    image: 'itzg/minecraft-server:latest',
    description: '开箱即用的 MC 服务端，世界存档在 /data。首次启动需要几分钟下载核心。',
    ports: [{ container: 25565, protocol: 'tcp', label: 'Minecraft' }],
    env: [
      { key: 'EULA', label: '同意 EULA', type: 'select', options: ['TRUE'], default: 'TRUE', required: true },
      { key: 'TYPE', label: '服务端类型', type: 'select', options: ['VANILLA', 'PAPER', 'FABRIC', 'FORGE'], default: 'PAPER' },
      { key: 'VERSION', label: '版本', type: 'text', default: 'LATEST' },
      { key: 'MEMORY', label: 'JVM 内存', type: 'text', default: '1500M' },
      { key: 'MAX_PLAYERS', label: '最大玩家数', type: 'text', default: '10' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'gitea',
    name: 'Gitea',
    icon: '🍵',
    category: '开发',
    image: 'gitea/gitea:latest',
    description: '轻量自建 Git 服务，含 Web 界面。',
    ports: [
      { container: 3000, protocol: 'tcp', label: 'Web' },
      { container: 22, protocol: 'tcp', label: 'SSH' },
    ],
    env: [{ key: 'USER_UID', label: 'UID', type: 'text', default: '1000' }],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    icon: '📈',
    category: '工具',
    image: 'louislam/uptime-kuma:1',
    description: '好看的服务可用性监控面板。',
    ports: [{ container: 3001, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/app/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    icon: '🔐',
    category: '工具',
    image: 'vaultwarden/server:latest',
    description: 'Bitwarden 兼容的密码库服务端。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'SIGNUPS_ALLOWED', label: '允许注册', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'ADMIN_TOKEN', label: '管理后台 Token', type: 'password', generate: 'password' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'n8n',
    name: 'n8n',
    icon: '🔗',
    category: '工具',
    image: 'n8nio/n8n:latest',
    description: '可视化自动化工作流。',
    ports: [{ container: 5678, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'N8N_BASIC_AUTH_ACTIVE', label: '启用基础认证', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'N8N_BASIC_AUTH_USER', label: '用户名', type: 'text', default: 'admin' },
      { key: 'N8N_BASIC_AUTH_PASSWORD', label: '密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/home/node/.n8n'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'ubuntu-shell',
    name: 'Ubuntu 沙盒',
    icon: '📦',
    category: '开发',
    image: 'ubuntu:24.04',
    description: '一个常驻的 Ubuntu 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'debian-shell',
    name: 'Debian 沙盒',
    icon: '🐧',
    category: '开发',
    image: 'debian:12',
    description: '一个常驻的 Debian 12 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'centos-shell',
    name: 'CentOS 沙盒',
    icon: '🎩',
    category: '开发',
    image: 'quay.io/centos/centos:stream9',
    description: '一个常驻的 CentOS Stream 9 容器，用面板里的「命令」页签执行 shell 命令。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/root'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'httpd',
    name: 'Apache HTTP Server',
    icon: '🪶',
    category: 'Web',
    image: 'httpd:2.4-alpine',
    description: '经典 Apache，网站文件放进数据卷的 /usr/local/apache2/htdocs。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/local/apache2/htdocs'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'caddy',
    name: 'Caddy 2',
    icon: '⚡',
    category: 'Web',
    image: 'caddy:2-alpine',
    description: '自带自动 HTTPS 的现代 Web 服务器，站点文件在 /usr/share/caddy，证书与状态在 /data。',
    ports: [{ container: 80, protocol: 'tcp', label: 'HTTP' }],
    env: [],
    volumes: ['/usr/share/caddy', '/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    icon: '📝',
    category: '建站',
    image: 'wordpress:php8.3-apache',
    description: '最流行的建站系统。需要先建一个 MySQL/MariaDB 实例，把它的容器名或 IP:端口填进下面。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'WORDPRESS_DB_HOST', label: '数据库地址（容器名或 IP:端口）', type: 'text', required: true },
      { key: 'WORDPRESS_DB_USER', label: '数据库用户', type: 'text', default: 'app', required: true },
      { key: 'WORDPRESS_DB_PASSWORD', label: '数据库密码', type: 'password', required: true },
      { key: 'WORDPRESS_DB_NAME', label: '数据库名', type: 'text', default: 'app', required: true },
    ],
    volumes: ['/var/www/html'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'halo',
    name: 'Halo 2',
    icon: '🌗',
    category: '建站',
    image: 'halohub/halo:2',
    description: '国产开源建站/博客系统，自带 H2 数据库，数据在 /root/.halo2。初始账号 admin。',
    ports: [{ container: 8090, protocol: 'tcp', label: 'Web' }],
    env: [
      {
        key: 'HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD',
        label: 'admin 初始密码',
        type: 'password',
        required: true,
        generate: 'password',
      },
    ],
    volumes: ['/root/.halo2'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    icon: '👻',
    category: '建站',
    image: 'ghost:5-alpine',
    description: '专注写作的博客平台，默认用 SQLite，内容在 /var/lib/ghost/content。',
    ports: [{ container: 2368, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'url', label: '站点地址（填面板给出的访问地址）', type: 'text', required: true },
    ],
    volumes: ['/var/lib/ghost/content'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    icon: '☁️',
    category: '建站',
    image: 'nextcloud:apache',
    description: '自建网盘 + 协作套件，默认使用 SQLite，数据在 /var/www/html。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'SQLITE_DATABASE', label: 'SQLite 库名', type: 'text', default: 'nextcloud' },
      { key: 'NEXTCLOUD_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'NEXTCLOUD_ADMIN_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
      { key: 'NEXTCLOUD_TRUSTED_DOMAINS', label: '信任域名（留空则任意）', type: 'text', default: '*' },
    ],
    volumes: ['/var/www/html'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'jupyter',
    name: 'Jupyter Notebook',
    icon: '📓',
    category: '开发',
    image: 'quay.io/jupyter/minimal-notebook:latest',
    description: '浏览器里的 Python 笔记本，工作目录持久化在 /home/jovyan/work。',
    ports: [{ container: 8888, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'JUPYTER_TOKEN', label: '访问 Token', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/home/jovyan/work'],
    defaults: { memoryMb: 2048, cpus: 1 },
  },
  {
    id: 'python-sandbox',
    name: 'Python 沙盒',
    icon: '🐍',
    category: '开发',
    image: 'python:3.12-slim',
    description: '常驻的 Python 3.12 容器，用「命令」页签跑脚本，代码放在 /workspace。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/workspace'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'node-sandbox',
    name: 'Node.js 沙盒',
    icon: '🟩',
    category: '开发',
    image: 'node:22-alpine',
    description: '常驻的 Node 22 容器，用「命令」页签跑 npm / node，代码放在 /workspace。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [],
    volumes: ['/workspace'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'go-sandbox',
    name: 'Go 沙盒',
    icon: '🐹',
    category: '开发',
    image: 'golang:1.26-alpine',
    description:
      '常驻的 Go 1.26 容器，用「命令」页签跑 go build / go run，代码放在 /workspace，模块缓存在 /go/pkg/mod。',
    cmd: ['sleep', 'infinity'],
    ports: [],
    env: [
      { key: 'GOPROXY', label: '模块代理', type: 'text', default: 'https://goproxy.cn,direct' },
    ],
    volumes: ['/workspace', '/go/pkg/mod'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'openssh',
    name: 'SSH 服务器',
    icon: '🔑',
    category: '开发',
    image: 'linuxserver/openssh-server:latest',
    description: '一个可以直接 SSH 登录的 Alpine 环境，配置在 /config。',
    ports: [{ container: 2222, protocol: 'tcp', label: 'SSH' }],
    env: [
      { key: 'USER_NAME', label: '登录用户名', type: 'text', default: 'dev', required: true },
      { key: 'PASSWORD_ACCESS', label: '允许密码登录', type: 'select', options: ['true', 'false'], default: 'true' },
      { key: 'USER_PASSWORD', label: '登录密码', type: 'password', required: true, generate: 'password' },
      { key: 'SUDO_ACCESS', label: '允许 sudo', type: 'select', options: ['true', 'false'], default: 'false' },
    ],
    volumes: ['/config'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'verdaccio',
    name: 'Verdaccio',
    icon: '📦',
    category: '开发',
    image: 'verdaccio/verdaccio:latest',
    description: '轻量 npm 私有仓库 / 缓存代理，包数据在 /verdaccio/storage。',
    ports: [{ container: 4873, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/verdaccio/storage'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'registry',
    name: 'Docker Registry',
    icon: '🐳',
    category: '开发',
    image: 'registry:2',
    description: '私有镜像仓库，镜像层存放在 /var/lib/registry。默认无鉴权，请配合内网使用。',
    ports: [{ container: 5000, protocol: 'tcp', label: 'Registry' }],
    env: [],
    volumes: ['/var/lib/registry'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'mailpit',
    name: 'Mailpit',
    icon: '📮',
    category: '开发',
    image: 'axllent/mailpit:latest',
    description: '开发用邮件捕获器：应用把邮件发到它的 SMTP，网页上就能看到。',
    ports: [
      { container: 8025, protocol: 'tcp', label: 'Web' },
      { container: 1025, protocol: 'tcp', label: 'SMTP' },
    ],
    env: [{ key: 'MP_DATABASE', label: '持久化文件', type: 'text', default: '/data/mailpit.db' }],
    volumes: ['/data'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'mariadb',
    name: 'MariaDB 11',
    icon: '🦭',
    category: '数据库',
    image: 'mariadb:11',
    description: 'MySQL 的社区分支，数据持久化在 /var/lib/mysql。',
    ports: [{ container: 3306, protocol: 'tcp', label: 'MariaDB' }],
    env: [
      { key: 'MARIADB_ROOT_PASSWORD', label: 'root 密码', type: 'password', required: true, generate: 'password' },
      { key: 'MARIADB_DATABASE', label: '默认数据库', type: 'text', default: 'app' },
      { key: 'MARIADB_USER', label: '普通用户', type: 'text', default: 'app' },
      { key: 'MARIADB_PASSWORD', label: '普通用户密码', type: 'password', generate: 'password' },
    ],
    volumes: ['/var/lib/mysql'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    icon: '🐇',
    category: '数据库',
    image: 'rabbitmq:3-management-alpine',
    description: '消息队列，带管理后台（15672）。数据在 /var/lib/rabbitmq。',
    ports: [
      { container: 5672, protocol: 'tcp', label: 'AMQP' },
      { container: 15672, protocol: 'tcp', label: '管理后台' },
    ],
    env: [
      { key: 'RABBITMQ_DEFAULT_USER', label: '用户名', type: 'text', default: 'admin', required: true },
      { key: 'RABBITMQ_DEFAULT_PASS', label: '密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/var/lib/rabbitmq'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'influxdb',
    name: 'InfluxDB 2',
    icon: '📉',
    category: '数据库',
    image: 'influxdb:2',
    description: '时序数据库，首次启动自动完成初始化，数据在 /var/lib/influxdb2。',
    ports: [{ container: 8086, protocol: 'tcp', label: 'HTTP API' }],
    env: [
      { key: 'DOCKER_INFLUXDB_INIT_MODE', label: '初始化模式', type: 'select', options: ['setup'], default: 'setup', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_USERNAME', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_PASSWORD', label: '管理员密码（≥8 位）', type: 'password', required: true, generate: 'password' },
      { key: 'DOCKER_INFLUXDB_INIT_ORG', label: '组织', type: 'text', default: 'my-org', required: true },
      { key: 'DOCKER_INFLUXDB_INIT_BUCKET', label: '默认 bucket', type: 'text', default: 'default', required: true },
    ],
    volumes: ['/var/lib/influxdb2'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    icon: '🏎️',
    category: '数据库',
    image: 'clickhouse/clickhouse-server:latest',
    description: '列式 OLAP 数据库，HTTP 接口在 8123，数据在 /var/lib/clickhouse。',
    ports: [{ container: 8123, protocol: 'tcp', label: 'HTTP' }],
    env: [
      { key: 'CLICKHOUSE_USER', label: '用户名', type: 'text', default: 'app', required: true },
      { key: 'CLICKHOUSE_PASSWORD', label: '密码', type: 'password', required: true, generate: 'password' },
      { key: 'CLICKHOUSE_DB', label: '默认数据库', type: 'text', default: 'app' },
    ],
    volumes: ['/var/lib/clickhouse'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'memcached',
    name: 'Memcached',
    icon: '🧠',
    category: '数据库',
    image: 'memcached:alpine',
    description: '纯内存缓存，没有持久化，重启即清空。',
    ports: [{ container: 11211, protocol: 'tcp', label: 'Memcached' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'meilisearch',
    name: 'Meilisearch',
    icon: '🔎',
    category: '数据库',
    image: 'getmeili/meilisearch:latest',
    description: '开箱即用的全文搜索引擎，索引数据在 /meili_data。',
    ports: [{ container: 7700, protocol: 'tcp', label: 'HTTP API' }],
    env: [
      { key: 'MEILI_MASTER_KEY', label: 'Master Key（≥16 位）', type: 'password', required: true, generate: 'password' },
      { key: 'MEILI_ENV', label: '运行模式', type: 'select', options: ['production', 'development'], default: 'production' },
    ],
    volumes: ['/meili_data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'adminer',
    name: 'Adminer',
    icon: '🗃️',
    category: '工具',
    image: 'adminer:latest',
    description: '单文件数据库管理界面，支持 MySQL / PostgreSQL / SQLite 等，无需持久化。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'filebrowser',
    name: 'File Browser',
    icon: '📂',
    category: '工具',
    image: 'filebrowser/filebrowser:s6',
    description: '网页版文件管理器，文件放在 /srv，配置库在 /database。初始账号 admin/admin，登录后请立刻改密。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/srv', '/database'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'syncthing',
    name: 'Syncthing',
    icon: '🔄',
    category: '工具',
    image: 'syncthing/syncthing:latest',
    description: '点对点文件同步，配置与同步目录都在 /var/syncthing。',
    ports: [
      { container: 8384, protocol: 'tcp', label: 'Web' },
      { container: 22000, protocol: 'tcp', label: '同步' },
    ],
    env: [],
    volumes: ['/var/syncthing'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'it-tools',
    name: 'IT Tools',
    icon: '🧰',
    category: '工具',
    image: 'corentinth/it-tools:latest',
    description: '一堆开发常用小工具（编解码、格式化、生成器）的合集网页，无需持久化。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: [],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'stirling-pdf',
    name: 'Stirling PDF',
    icon: '📄',
    category: '工具',
    image: 'stirlingtools/stirling-pdf:latest',
    description: '本地跑的 PDF 全能工具箱：合并、拆分、压缩、OCR。配置在 /configs。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/configs'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'memos',
    name: 'Memos',
    icon: '🗒️',
    category: '工具',
    image: 'neosmemo/memos:stable',
    description: '轻量自建笔记 / 想法流，数据在 /var/opt/memos。',
    ports: [{ container: 5230, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/opt/memos'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'grafana',
    name: 'Grafana',
    icon: '📊',
    category: '工具',
    image: 'grafana/grafana:latest',
    description: '数据可视化与仪表盘，仪表盘数据在 /var/lib/grafana。',
    ports: [{ container: 3000, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'GF_SECURITY_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'GF_SECURITY_ADMIN_PASSWORD', label: '管理员密码', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/var/lib/grafana'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    icon: '🔍',
    category: '工具',
    image: 'searxng/searxng:latest',
    description: '自建聚合搜索引擎，不记录隐私。配置在 /etc/searxng，首次启动自动生成。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'SEARXNG_BASE_URL', label: '站点地址（填面板给出的访问地址）', type: 'text' }],
    volumes: ['/etc/searxng'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'freshrss',
    name: 'FreshRSS',
    icon: '📰',
    category: '工具',
    image: 'freshrss/freshrss:latest',
    description: '自建 RSS 阅读器，数据在 /var/www/FreshRSS/data。',
    ports: [{ container: 80, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/var/www/FreshRSS/data', '/var/www/FreshRSS/extensions'],
    defaults: { memoryMb: 512, cpus: 0.5 },
  },
  {
    id: 'nocodb',
    name: 'NocoDB',
    icon: '🧮',
    category: '工具',
    image: 'nocodb/nocodb:latest',
    description: '把数据库变成 Airtable 那样的表格界面，自带 SQLite，数据在 /usr/app/data。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/usr/app/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'homer',
    name: 'Homer',
    icon: '🏠',
    category: '工具',
    image: 'b4bz/homer:latest',
    description: '静态服务导航页，编辑数据卷里 /www/assets/config.yml 就能改。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/www/assets'],
    defaults: { memoryMb: 256, cpus: 0.5 },
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    icon: '🌀',
    category: '工具',
    image: 'linuxserver/qbittorrent:latest',
    description: '带网页界面的 BT 客户端，下载目录 /downloads，配置 /config。首次登录用户名 admin，密码见容器日志。',
    ports: [
      { container: 8080, protocol: 'tcp', label: 'Web' },
      { container: 6881, protocol: 'tcp', label: 'BT' },
    ],
    env: [
      { key: 'WEBUI_PORT', label: 'Web 端口', type: 'text', default: '8080', required: true },
      { key: 'PUID', label: 'UID', type: 'text', default: '1000' },
      { key: 'PGID', label: 'GID', type: 'text', default: '1000' },
    ],
    volumes: ['/config', '/downloads'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    icon: '🎬',
    category: '媒体',
    image: 'jellyfin/jellyfin:latest',
    description: '开源影音媒体库，把片子放进数据卷的 /media，配置在 /config。',
    ports: [{ container: 8096, protocol: 'tcp', label: 'Web' }],
    env: [],
    volumes: ['/config', '/media'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    icon: '🎵',
    category: '媒体',
    image: 'deluan/navidrome:latest',
    description: '自建音乐流媒体，兼容 Subsonic 客户端。音乐放 /music，索引在 /data。',
    ports: [{ container: 4533, protocol: 'tcp', label: 'Web' }],
    env: [{ key: 'ND_LOGLEVEL', label: '日志级别', type: 'select', options: ['error', 'info', 'debug'], default: 'info' }],
    volumes: ['/data', '/music'],
    defaults: { memoryMb: 512, cpus: 1 },
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    icon: '🖼️',
    category: '媒体',
    image: 'photoprism/photoprism:latest',
    description: 'AI 相册管理，原图放 /photoprism/originals，索引与缩略图在 /photoprism/storage。',
    ports: [{ container: 2342, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'PHOTOPRISM_ADMIN_USER', label: '管理员用户名', type: 'text', default: 'admin', required: true },
      { key: 'PHOTOPRISM_ADMIN_PASSWORD', label: '管理员密码（≥8 位）', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/photoprism/storage', '/photoprism/originals'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'open-webui',
    name: 'Open WebUI',
    icon: '💬',
    category: 'AI',
    image: 'ghcr.io/open-webui/open-webui:main',
    description: '类 ChatGPT 的自托管前端，可接 Ollama 或任意 OpenAI 兼容接口，数据在 /app/backend/data。',
    ports: [{ container: 8080, protocol: 'tcp', label: 'Web' }],
    env: [
      { key: 'WEBUI_SECRET_KEY', label: '会话密钥', type: 'password', required: true, generate: 'password' },
      { key: 'OPENAI_API_BASE_URL', label: 'OpenAI 兼容接口地址', type: 'text', default: 'https://api.openai.com/v1' },
      { key: 'OPENAI_API_KEY', label: 'API Key（可留空）', type: 'password' },
    ],
    volumes: ['/app/backend/data'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    category: 'AI',
    image: 'ollama/ollama:latest',
    description: '本地大模型运行时（纯 CPU 推理较慢），模型权重存在 /root/.ollama，用「命令」页签 ollama pull 拉模型。',
    ports: [{ container: 11434, protocol: 'tcp', label: 'API' }],
    env: [],
    volumes: ['/root/.ollama'],
    defaults: { memoryMb: 4096, cpus: 4 },
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    icon: '🦞',
    category: 'AI',
    image: 'openclaw/openclaw:latest',
    description: '跑在自己设备上的个人 AI 助手网关：接任意模型（OpenAI / Anthropic / 本地模型），从 Telegram、WhatsApp、Discord 等渠道收发消息。首次启动后打开 18789 的网页控制台完成初始化。',
    cmd: ['node', 'dist/index.js', 'gateway', '--bind', 'lan', '--port', '18789'],
    ports: [{ container: 18789, protocol: 'tcp', label: '控制台' }],
    env: [
      { key: 'OPENCLAW_GATEWAY_TOKEN', label: '网关 Token（控制台登录用）', type: 'password', generate: 'password' },
    ],
    volumes: ['/home/node/.openclaw', '/home/node/.config/openclaw'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'hermes',
    name: 'Hermes Agent',
    icon: '☤',
    category: 'AI',
    image: 'nousresearch/hermes-agent:latest',
    description: 'Nous Research 的自进化 AI 代理：技能从经验中自学、跨会话记忆，从 Telegram / Discord / Slack / WhatsApp 收发消息。网关只主动外连、无入站端口；配置请用「控制台」跑 hermes setup，或直接编辑数据卷里的 hermes.json。',
    cmd: ['gateway', 'run'],
    ports: [],
    env: [],
    volumes: ['/opt/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'minecraft-bedrock',
    name: 'Minecraft 基岩版服务器',
    icon: '🧱',
    category: '游戏',
    image: 'itzg/minecraft-bedrock-server:latest',
    description: '手机 / 主机 / Win10 版能进的基岩版服务端，存档在 /data。UDP 服务不支持闲时休眠。',
    ports: [{ container: 19132, protocol: 'udp', label: 'Bedrock' }],
    env: [
      { key: 'EULA', label: '同意 EULA', type: 'select', options: ['TRUE'], default: 'TRUE', required: true },
      { key: 'VERSION', label: '版本', type: 'text', default: 'LATEST' },
      { key: 'SERVER_NAME', label: '服务器名', type: 'text', default: 'Bedrock Server' },
      { key: 'GAMEMODE', label: '游戏模式', type: 'select', options: ['survival', 'creative', 'adventure'], default: 'survival' },
      { key: 'DIFFICULTY', label: '难度', type: 'select', options: ['peaceful', 'easy', 'normal', 'hard'], default: 'easy' },
    ],
    volumes: ['/data'],
    defaults: { memoryMb: 1024, cpus: 1 },
  },
  {
    id: 'factorio',
    name: 'Factorio 服务器',
    icon: '🏭',
    category: '游戏',
    image: 'factoriotools/factorio:stable',
    description: '异星工厂多人服务端，存档与配置在 /factorio。UDP 服务不支持闲时休眠。',
    ports: [{ container: 34197, protocol: 'udp', label: 'Factorio' }],
    env: [],
    volumes: ['/factorio'],
    defaults: { memoryMb: 2048, cpus: 2 },
  },
  {
    id: 'valheim',
    name: 'Valheim 服务器',
    icon: '🛡️',
    category: '游戏',
    image: 'lloesche/valheim-server:latest',
    description: '英灵神殿专用服务端，存档在 /config。首次启动要下载几 GB，UDP 服务不支持闲时休眠。',
    ports: [
      { container: 2456, protocol: 'udp', label: '游戏' },
      { container: 2457, protocol: 'udp', label: '查询' },
    ],
    env: [
      { key: 'SERVER_NAME', label: '服务器名', type: 'text', default: 'Valheim', required: true },
      { key: 'WORLD_NAME', label: '世界名', type: 'text', default: 'Dedicated', required: true },
      { key: 'SERVER_PASS', label: '进服密码（≥5 位）', type: 'password', required: true, generate: 'password' },
    ],
    volumes: ['/config'],
    defaults: { memoryMb: 4096, cpus: 2 },
  },
];

export const templateById = (id) => TEMPLATES.find((t) => t.id === id) || null;

/** Strips nothing today, but keeps a single place to control what the client sees. */
export const publicTemplates = () => TEMPLATES;
